ALTER TABLE PUBLIC.CARDS ADD SECONDARY_FEATURE INTEGER DEFAULT -420 NOT NULL;
ALTER TABLE PUBLIC.CARDS ADD TERNARY_FEATURE INTEGER DEFAULT -420 NOT NULL;
ALTER TABLE PUBLIC.CARDS ADD primary_FEATURE INTEGER DEFAULT -420 NOT NULL;
ALTER TABLE PUBLIC.CARDS ADD maxrepair INTEGER DEFAULT -420 NOT NULL;
